/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 chair.glb -T -p 6
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Chair(props) {
  const { nodes, materials } = useGLTF("/models/chair-transformed.glb");

  for (const material of Object.values(materials)) {
    material.envMapIntensity = 0.4;
  }

  materials.Fabric.roughness = 1;

  return (
    <group
      {...props}
      dispose={null}
    >
      <group
        position={[1.259678, 0.001911, -0.935999]}
        scale={1.175594}
      >
        <mesh
          geometry={nodes.Office_Chair_1.geometry}
          material={materials.Fabric}
        />
        <mesh
          geometry={nodes.Office_Chair_2.geometry}
          material={materials.Plastic}
        />
        <mesh
          geometry={nodes.Office_Chair_3.geometry}
          material={materials.BlackGloss}
        />
        <mesh
          geometry={nodes.Office_Chair_4.geometry}
          material={materials.Metal}
        />
      </group>
    </group>
  );
}
