/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 desk.glb -T -p 6
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { LinearSRGBColorSpace } from "three";

export function Desk(props) {
  const { nodes, materials } = useGLTF("/models/desk-transformed.glb");
  materials["Material.001"].roughness = 1;
  materials["Material.001"].envMapIntensity = 0;

  const lm = useTexture("/textures/desk/Desk_Bake4_CyclesBake_DIFFUSE.jpg");
  lm.flipY = false;
  lm.colorSpace = LinearSRGBColorSpace;
  materials["Material.001"].lightMap = lm;
  materials["Material.001"].lightMapIntensity = 2.5;
  materials["Material.002"].roughness = 0.8;

  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes.Desk.geometry}
        material={materials["Material.001"]}
        position={[1.232791, 0.673351, -0.01]}
      />
      <mesh
        geometry={nodes.Leg.geometry}
        material={materials["Material.002"]}
        position={[1.83731, 0.01938, -0.09771]}
      />
      <mesh
        geometry={nodes.Remote.geometry}
        material={materials["Material.002"]}
        position={[0.710144, 0.658045, -0.610869]}
        rotation={[-Math.PI / 4, 0, 0]}
        scale={[0.6832, 0.801298, 0.801298]}
      />
    </group>
  );
}
